### ISSUE TITLE
Five digit story numbers not being found

### ISSUE THREAD

**Issue by benbelly** [RallyTools/RallyRestAPIForClojure#17]
This seems crazy, and maybe I'm seeing symptoms where they don't exist, but...
`(rally/find-by-formatted-id rally-api :userstory "S2750")` works, and 
`(rally/find-by-formatted-id rally-api :userstory "S27500")` does not work, even though both stories exist. I am not able to retrieve that or any other stories with 5-digit formatted ids.

**Comment by mtbkapp** [comment]
@benbelly I know it's been nearly a year. I tried to repro this and I couldn't. However, I thought I did when I didn't have my project scope set correctly.
`(rally.api.request/set-current-project api (find-by-id api :project project-id))` returns a *new* api object with the new project scoping.

**Comment by benbelly** [comment]
Sorry for the delay getting back. That was exactly my problem! Thanks for the help!!
